# Milestone 1: Data Profiling

Profil awal dataset CommonLingua-Train menggunakan Polars LazyFrame dan DuckDB. Dataset lokal terdiri dari dua file CSV (`commonlingua_train.csv` dan `commonlingua_validation.csv`) dengan kolom seperti `text`, `lang`, `source`, dan metadata lainnya. Notebook ini membaca file mentah tanpa mengubahnya.

Jalankan notebook dari folder proyek atau folder `notebooks`. Proses profiling membaca isi file; karena dataset berukuran besar, proses agregasi dapat memerlukan waktu.

In [26]:
%pip install duckdb polars

Requirement already satisfied: duckdb in c:\users\imam prayuda\appdata\local\programs\python\python313\lib\site-packages (2.0.0)
Requirement already satisfied: polars in c:\users\imam prayuda\appdata\local\programs\python\python313\lib\site-packages (2.0.0)
Requirement already satisfied: polars-runtime-32==2.0.0 in c:\users\imam prayuda\appdata\local\programs\python\python313\lib\site-packages (from polars) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [27]:
from pathlib import Path

import duckdb
import polars as pl

PROJECT_ROOT = Path.cwd().resolve()
if PROJECT_ROOT.name == 'notebooks':
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / 'data' / 'raw'
DATA_FILES = {
    'train': DATA_DIR / 'commonlingua_train.csv',
    'validation': DATA_DIR / 'commonlingua_validation.csv',
}

missing_files = [path for path in DATA_FILES.values() if not path.exists()]
if missing_files:
    missing_list = '\n'.join(str(path) for path in missing_files)
    raise FileNotFoundError(
        f'File dataset tidak ditemukan:\n{missing_list}\n'
        'Pastikan kedua CSV tersedia di data/raw/.'
    )

for split, path in DATA_FILES.items():
    size_mb = path.stat().st_size / 1_000_000
    print(f'{split}: {path.name} ({size_mb:,.1f} MB)')

train: commonlingua_train.csv (2,065.0 MB)
validation: commonlingua_validation.csv (226.5 MB)

## Profil Polars

`scan_csv` membangun query lazy; data dibaca saat `collect()` dipanggil. Profil berikut menghitung jumlah baris dan nilai null per kolom untuk masing-masing split.

In [28]:
def scan_dataset(path: Path) -> pl.LazyFrame:
    return pl.scan_csv(
        path,
        infer_schema_length=10_000,
        null_values=['', 'NULL', 'null'],
        try_parse_dates=False,
        low_memory=True,
    )


lazy_data = {split: scan_dataset(path) for split, path in DATA_FILES.items()}
profil_polars = {}

for split, frame in lazy_data.items():
    print(f'\nSkema {split}:')
    print(frame.collect_schema())

    ringkasan = frame.select(
        pl.len().alias('jumlah_baris'),
        pl.all().null_count().name.suffix('_null'),
    ).collect()
    profil_polars[split] = ringkasan
    print(f'Ringkasan {split}:')
    display(ringkasan)

Skema train:
Schema({'text': String, 'lang': String, 'source': String, 'identifier': String, 'title': String, 'collection': String, 'license': String, 'open_type': String, 'creator': String, 'date': String})
Ringkasan train:

shape: (1, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ jumlah_ba ┆ text_null ┆ lang_null ┆ source_nu ┆ … ┆ license_n ┆ open_type ┆ creator_n ┆ date_nul │
│ ris       ┆ ---       ┆ ---       ┆ ll        ┆   ┆ ull       ┆ _null     ┆ ull       ┆ l        │
│ ---       ┆ u32       ┆ u32       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ u32       ┆           ┆           ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2482568   ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 26693     ┆ 26693     ┆ 2480877   ┆ 56236    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Skema validation:
Schema({'text': String, 'lang': String, 'source': String, 'identifier': String, 'title': String, 'collection': String, 'license': String, 'open_type': String, 'creator': String, 'date': String})
Ringkasan validation:

shape: (1, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ jumlah_ba ┆ text_null ┆ lang_null ┆ source_nu ┆ … ┆ license_n ┆ open_type ┆ creator_n ┆ date_nul │
│ ris       ┆ ---       ┆ ---       ┆ ll        ┆   ┆ ull       ┆ _null     ┆ ull       ┆ l        │
│ ---       ┆ u32       ┆ u32       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ u32       ┆           ┆           ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 272875    ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 272694    ┆ 3228     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Ringkasan Profiling

Jalankan sel kode berikut setelah profiling Polars untuk menampilkan ringkasan dataset.

In [29]:
jumlah_file = len(DATA_FILES)
ukuran_total_byte = sum(path.stat().st_size for path in DATA_FILES.values())
ukuran_total_gb = ukuran_total_byte / 1_000_000_000
jumlah_baris_per_split = {
    split: int(ringkasan['jumlah_baris'][0])
    for split, ringkasan in profil_polars.items()
}
jumlah_baris_total = sum(jumlah_baris_per_split.values())
jumlah_baris_format = f'{jumlah_baris_total:,}'.replace(',', '.')
ukuran_total_gb_format = f'{ukuran_total_gb:.2f}'.replace('.', ',')
jumlah_kolom_per_split = {
    split: len(frame.collect_schema().names())
    for split, frame in lazy_data.items()
}

if len(set(jumlah_kolom_per_split.values())) == 1:
    jumlah_kolom = str(next(iter(jumlah_kolom_per_split.values())))
else:
    jumlah_kolom = ', '.join(
        f'{split}: {jumlah}'
        for split, jumlah in jumlah_kolom_per_split.items()
    )

lebih_dari_satu_juta_baris = jumlah_baris_total > 1_000_000
minimal_lima_ratus_mb = ukuran_total_byte >= 500_000_000
memenuhi_syarat = lebih_dari_satu_juta_baris and minimal_lima_ratus_mb

print('=== RINGKASAN PROFILING ===')
print(f'Jumlah file        : {jumlah_file}')
print(f'Ukuran dataset     : {ukuran_total_gb_format} GB')
print(f'Jumlah baris       : {jumlah_baris_format}')
print(f'Jumlah kolom       : {jumlah_kolom}')
print(f'> 1 juta baris     : {"YA" if lebih_dari_satu_juta_baris else "TIDAK"}')
print(f'>= 500 MB          : {"YA" if minimal_lima_ratus_mb else "TIDAK"}')
print(f'Memenuhi syarat    : {"YA" if memenuhi_syarat else "TIDAK"}')

=== RINGKASAN PROFILING ===
Jumlah file        : 2
Ukuran dataset     : 2,29 GB
Jumlah baris       : 2.755.443
Jumlah kolom       : 10
> 1 juta baris     : YA
>= 500 MB          : YA
Memenuhi syarat    : YA

### Kesimpulan

Berdasarkan hasil profiling, dataset CommonLingua terdiri atas file train dan validation. Jumlah baris, ukuran total, serta jumlah kolom ditampilkan pada ringkasan di atas. Dataset memenuhi kriteria apabila jumlah barisnya lebih dari 1 juta dan ukuran totalnya minimal 500 MB.

### Contoh data

Ambil beberapa baris pertama dari setiap split untuk melihat bentuk rekaman tanpa mengumpulkan seluruh dataset.

In [30]:
for split, frame in lazy_data.items():
    print(f'Contoh {split}:')
    display(frame.head(5).collect())

Contoh train:

shape: (5, 10)
┌───────────────┬──────┬───────────┬───────────────┬───┬──────────┬───────────────┬─────────┬──────┐
│ text          ┆ lang ┆ source    ┆ identifier    ┆ … ┆ license  ┆ open_type     ┆ creator ┆ date │
│ ---           ┆ ---  ┆ ---       ┆ ---           ┆   ┆ ---      ┆ ---           ┆ ---     ┆ ---  │
│ str           ┆ str  ┆ str       ┆ str           ┆   ┆ str      ┆ str           ┆ str     ┆ str  │
╞═══════════════╪══════╪═══════════╪═══════════════╪═══╪══════════╪═══════════════╪═════════╪══════╡
│ 55°51′16.63″  ┆ lit  ┆ Wikipedia ┆ https://lt.wi ┆ … ┆ CC-BY-SA ┆ Web           ┆ null    ┆ 2026 │
│ š. pl.        ┆      ┆           ┆ kipedia.org/w ┆   ┆          ┆               ┆         ┆      │
│ 22°23′53.2…   ┆      ┆           ┆ iki/…         ┆   ┆          ┆               ┆         ┆      │
│ Thành phố     ┆ vie  ┆ Wikipedia ┆ https://vi.wi ┆ … ┆ CC-BY-SA ┆ Web           ┆ null    ┆ 2026 │
│ Thiên Tân     ┆      ┆           ┆ kipedia.org/w ┆   ┆          ┆               ┆         ┆      │
│               ┆      ┆           ┆ iki/…         ┆   ┆          ┆               ┆         ┆      │
│ - Bột Hải…    ┆      ┆           ┆               ┆   ┆          ┆               ┆         ┆      │
│ Ou konsidere  ┆ hat  ┆ eBible    ┆ null          ┆ … ┆ Public   ┆ Open_Culture  ┆ null    ┆ 1985 │
│ mechan ki sou ┆      ┆           ┆               ┆   ┆ Domain   ┆               ┆         ┆      │
│ lat…          ┆      ┆           ┆               ┆   ┆          ┆               ┆         ┆      │
│ Vzreja        ┆ slv  ┆ Wikipedia ┆ https://sl.wi ┆ … ┆ CC-BY-SA ┆ Web           ┆ null    ┆ 2026 │
│               ┆      ┆           ┆ kipedia.org/w ┆   ┆          ┆               ┆         ┆      │
│ Takahē z      ┆      ┆           ┆ iki/…         ┆   ┆          ┆               ┆         ┆      │
│ Južnega       ┆      ┆           ┆               ┆   ┆          ┆               ┆         ┆      │
│ otoka…        ┆      ┆           ┆               ┆   ┆          ┆               ┆         ┆      │
│ Loïens        ┆ pcd  ┆ Wikipedia ┆ https://pcd.w ┆ … ┆ CC-BY-SA ┆ Web           ┆ null    ┆ 2026 │
│ éstérnes      ┆      ┆           ┆ ikipedia.org/ ┆   ┆          ┆               ┆         ┆      │
│               ┆      ┆           ┆ wiki…         ┆   ┆          ┆               ┆         ┆      │
│ - Zen-On      ┆      ┆           ┆               ┆   ┆          ┆               ┆         ┆      │
│ Cont…         ┆      ┆           ┆               ┆   ┆          ┆               ┆         ┆      │
└───────────────┴──────┴───────────┴───────────────┴───┴──────────┴───────────────┴─────────┴──────┘

Contoh validation:

shape: (5, 10)
┌─────────────────┬──────┬───────────┬─────────────────┬───┬──────────┬───────────┬─────────┬──────┐
│ text            ┆ lang ┆ source    ┆ identifier      ┆ … ┆ license  ┆ open_type ┆ creator ┆ date │
│ ---             ┆ ---  ┆ ---       ┆ ---             ┆   ┆ ---      ┆ ---       ┆ ---     ┆ ---  │
│ str             ┆ str  ┆ str       ┆ str             ┆   ┆ str      ┆ str       ┆ str     ┆ str  │
╞═════════════════╪══════╪═══════════╪═════════════════╪═══╪══════════╪═══════════╪═════════╪══════╡
│ Venera (simvol: ┆ tly  ┆ Wikipedia ┆ https://tly.wik ┆ … ┆ CC-BY-SA ┆ Web       ┆ null    ┆ 2026 │
│ ) — Həši siste… ┆      ┆           ┆ ipedia.org/wiki ┆   ┆          ┆           ┆         ┆      │
│                 ┆      ┆           ┆ …               ┆   ┆          ┆           ┆         ┆      │
│ Lapkristė 14    ┆ sgs  ┆ Wikipedia ┆ https://bat-smg ┆ … ┆ CC-BY-SA ┆ Web       ┆ null    ┆ 2026 │
│ dėina īr 318    ┆      ┆           ┆ .wikipedia.org/ ┆   ┆          ┆           ┆         ┆      │
│ metu…           ┆      ┆           ┆ …               ┆   ┆          ┆           ┆         ┆      │
│ Gweler hefyd    ┆ cym  ┆ Wikipedia ┆ https://cy.wiki ┆ … ┆ CC-BY-SA ┆ Web       ┆ null    ┆ 2026 │
│                 ┆      ┆           ┆ pedia.org/wiki/ ┆   ┆          ┆           ┆         ┆      │
│ Cyhoeddodd      ┆      ┆           ┆ …               ┆   ┆          ┆           ┆         ┆      │
│ Danie…          ┆      ┆           ┆                 ┆   ┆          ┆           ┆         ┆      │
│ Comestibilità   ┆ pms  ┆ Wikipedia ┆ https://pms.wik ┆ … ┆ CC-BY-SA ┆ Web       ┆ null    ┆ 2026 │
│                 ┆      ┆           ┆ ipedia.org/wiki ┆   ┆          ┆           ┆         ┆      │
│ A venta mai     ┆      ┆           ┆ …               ┆   ┆          ┆           ┆         ┆      │
│ man…            ┆      ┆           ┆                 ┆   ┆          ┆           ┆         ┆      │
│ Самостоятелни   ┆ bul  ┆ Wikipedia ┆ https://bg.wiki ┆ … ┆ CC-BY-SA ┆ Web       ┆ null    ┆ 2026 │
│ романи          ┆      ┆           ┆ pedia.org/wiki/ ┆   ┆          ┆           ┆         ┆      │
│                 ┆      ┆           ┆ …               ┆   ┆          ┆           ┆         ┆      │
│ - The Po…       ┆      ┆           ┆                 ┆   ┆          ┆           ┆         ┆      │
└─────────────────┴──────┴───────────┴─────────────────┴───┴──────────┴───────────┴─────────┴──────┘

## Profil DuckDB

DuckDB membaca CSV langsung dari disk dan menampilkan statistik ringkas per kolom. `SUMMARIZE` memindai data sehingga eksekusinya dapat memerlukan waktu. `strict_mode=false` membuat DuckDB tetap membaca CSV ketika menemukan baris dengan format tidak konsisten; periksa data sumber jika nilai pada baris bermasalah perlu dipastikan.

In [31]:
connection = duckdb.connect()
profil_duckdb = {}

for split, path in DATA_FILES.items():
    relation = connection.sql(
        'SUMMARIZE SELECT * FROM read_csv_auto(?, strict_mode=false, parallel=false)',
        params=[str(path)],
    )
    profil_duckdb[split] = pl.DataFrame(
        relation.fetchall(),
        schema=relation.columns,
        orient='row',
    )
    print(f'Profil DuckDB {split}:')
    display(profil_duckdb[split])

Profil DuckDB train:

shape: (10, 12)
┌─────────────┬─────────────┬──────────────┬─────────────┬───┬──────┬──────┬─────────┬─────────────┐
│ column_name ┆ column_type ┆ min          ┆ max         ┆ … ┆ q50  ┆ q75  ┆ count   ┆ null_percen │
│ ---         ┆ ---         ┆ ---          ┆ ---         ┆   ┆ ---  ┆ ---  ┆ ---     ┆ tage        │
│ str         ┆ str         ┆ str          ┆ str         ┆   ┆ null ┆ null ┆ i64     ┆ ---         │
│             ┆             ┆              ┆             ┆   ┆      ┆      ┆         ┆ decimal[38, │
│             ┆             ┆              ┆             ┆   ┆      ┆      ┆         ┆ 2]          │
╞═════════════╪═════════════╪══════════════╪═════════════╪═══╪══════╪══════╪═════════╪═════════════╡
│ text        ┆ VARCHAR     ┆  ┆ 𱎼家话，又  ┆ … ┆ null ┆ null ┆ 2482568 ┆ 0.00        │
│             ┆             ┆  ┆ 叫重安江苗  ┆   ┆      ┆      ┆         ┆             │
│             ┆             ┆ …      ┆ 语，是汉藏  ┆   ┆      ┆      ┆         ┆             │
│             ┆             ┆              ┆ 语系苗瑶语  ┆   ┆      ┆      ┆         ┆             │
│             ┆             ┆              ┆ 族一種闲话  ┆   ┆      ┆      ┆         ┆             │
│             ┆             ┆              ┆ 。          ┆   ┆      ┆      ┆         ┆             │
│             ┆             ┆              ┆             ┆   ┆      ┆      ┆         ┆             │
│             ┆             ┆              ┆ 张济…       ┆   ┆      ┆      ┆         ┆             │
│ lang        ┆ VARCHAR     ┆ abk          ┆ zul         ┆ … ┆ null ┆ null ┆ 2482568 ┆ 0.00        │
│ source      ┆ VARCHAR     ┆ Anno         ┆ usc         ┆ … ┆ null ┆ null ┆ 2482568 ┆ 0.00        │
│ identifier  ┆ VARCHAR     ┆ -0xVHB9387w_ ┆ （××××）××  ┆ … ┆ null ┆ null ┆ 2482568 ┆ 0.56        │
│             ┆             ┆ 1            ┆ 执异字第××  ┆   ┆      ┆      ┆         ┆             │
│             ┆             ┆              ┆ 号          ┆   ┆      ┆      ┆         ┆             │
│ title       ┆ VARCHAR     ┆              ┆ 󠀦󠀢󠀤󠀙󠀜󠀚󠀛-󠀦󠀢󠀤󠀙󠀜󠀚󠀛           ┆ … ┆ null ┆ null ┆ 2482568 ┆ 1.90        │
│             ┆             ┆ DARDUMAR     ┆             ┆   ┆      ┆      ┆         ┆             │
│             ┆             ┆ VOA: Yadda   ┆             ┆   ┆      ┆      ┆         ┆             │
│             ┆             ┆ Matashiya…   ┆             ┆   ┆      ┆      ┆         ┆             │
│ collection  ┆ VARCHAR     ┆ Achaemenid   ┆ usc         ┆ … ┆ null ┆ null ┆ 2482568 ┆ 1.17        │
│             ┆             ┆ Royal        ┆             ┆   ┆      ┆      ┆         ┆             │
│             ┆             ┆ Inscriptions ┆             ┆   ┆      ┆      ┆         ┆             │
│             ┆             ┆ …            ┆             ┆   ┆      ┆      ┆         ┆             │
│ license     ┆ VARCHAR     ┆ CC-BY-SA     ┆ Various     ┆ … ┆ null ┆ null ┆ 2482568 ┆ 1.08        │
│             ┆             ┆              ┆ open        ┆   ┆      ┆      ┆         ┆             │
│             ┆             ┆              ┆ science     ┆   ┆      ┆      ┆         ┆             │
│ open_type   ┆ VARCHAR     ┆ Open_Culture ┆ Web         ┆ … ┆ null ┆ null ┆ 2482568 ┆ 1.08        │
│ creator     ┆ VARCHAR     ┆ Barat et al. ┆ Masoretic   ┆ … ┆ null ┆ null ┆ 2482568 ┆ 99.93       │
│ date        ┆ VARCHAR     ┆ -100         ┆ <NA>        ┆ … ┆ null ┆ null ┆ 2482568 ┆ 2.27        │
└─────────────┴─────────────┴──────────────┴─────────────┴───┴──────┴──────┴─────────┴─────────────┘

Profil DuckDB validation:

shape: (10, 12)
┌─────────────┬─────────────┬──────────────┬──────────────┬───┬──────┬──────┬────────┬─────────────┐
│ column_name ┆ column_type ┆ min          ┆ max          ┆ … ┆ q50  ┆ q75  ┆ count  ┆ null_percen │
│ ---         ┆ ---         ┆ ---          ┆ ---          ┆   ┆ ---  ┆ ---  ┆ ---    ┆ tage        │
│ str         ┆ str         ┆ str          ┆ str          ┆   ┆ null ┆ null ┆ i64    ┆ ---         │
│             ┆             ┆              ┆              ┆   ┆      ┆      ┆        ┆ decimal[38, │
│             ┆             ┆              ┆              ┆   ┆      ┆      ┆        ┆ 2]          │
╞═════════════╪═════════════╪══════════════╪══════════════╪═══╪══════╪══════╪════════╪═════════════╡
│ text        ┆ VARCHAR     ┆    ┆ 𧒽崗站（粵拼 ┆ … ┆ null ┆ null ┆ 272875 ┆ 0.00        │
│             ┆             ┆       ┆ ：leoi1      ┆   ┆      ┆      ┆        ┆             │
│             ┆             ┆ Abstract: T… ┆ gong1 zaam6  ┆   ┆      ┆      ┆        ┆             │
│             ┆             ┆              ┆ ，英文：Le…  ┆   ┆      ┆      ┆        ┆             │
│ lang        ┆ VARCHAR     ┆ abk          ┆ zul          ┆ … ┆ null ┆ null ┆ 272875 ┆ 0.00        │
│ source      ┆ VARCHAR     ┆ Anno         ┆ reg_docs     ┆ … ┆ null ┆ null ┆ 272875 ┆ 0.00        │
│ identifier  ┆ VARCHAR     ┆ 0000213163_3 ┆ （2021）黔05 ┆ … ┆ null ┆ null ┆ 272875 ┆ 0.57        │
│             ┆             ┆ 4            ┆ 02民初12481  ┆   ┆      ┆      ┆        ┆             │
│             ┆             ┆              ┆ 号           ┆   ┆      ┆      ┆        ┆             │
│ title       ┆ VARCHAR     ┆              ┆ 𧒽崗站       ┆ … ┆ null ┆ null ┆ 272875 ┆ 1.91        │
│             ┆             ┆ Gaza,        ┆ (地鐵)       ┆   ┆      ┆      ┆        ┆             │
│             ┆             ┆ sigidadenw   ┆              ┆   ┆      ┆      ┆        ┆             │
│             ┆             ┆ tina se ka   ┆              ┆   ┆      ┆      ┆        ┆             │
│             ┆             ┆ s…           ┆              ┆   ┆      ┆      ┆        ┆             │
│ collection  ┆ VARCHAR     ┆ Achaemenid   ┆ riao/The     ┆ … ┆ null ┆ null ┆ 272875 ┆ 0.10        │
│             ┆             ┆ Royal        ┆ Royal        ┆   ┆      ┆      ┆        ┆             │
│             ┆             ┆ Inscriptions ┆ Inscriptions ┆   ┆      ┆      ┆        ┆             │
│             ┆             ┆ …            ┆ of…          ┆   ┆      ┆      ┆        ┆             │
│ license     ┆ VARCHAR     ┆ CC-BY-SA     ┆ Various open ┆ … ┆ null ┆ null ┆ 272875 ┆ 0.00        │
│             ┆             ┆              ┆ science      ┆   ┆      ┆      ┆        ┆             │
│ open_type   ┆ VARCHAR     ┆ Open_Culture ┆ Web          ┆ … ┆ null ┆ null ┆ 272875 ┆ 0.00        │
│ creator     ┆ VARCHAR     ┆ Barat et al. ┆ Masoretic    ┆ … ┆ null ┆ null ┆ 272875 ┆ 99.93       │
│ date        ┆ VARCHAR     ┆ -113         ┆ <NA>         ┆ … ┆ null ┆ null ┆ 272875 ┆ 1.18        │
└─────────────┴─────────────┴──────────────┴──────────────┴───┴──────┴──────┴────────┴─────────────┘

## Catatan Milestone 1

Isi temuan berdasarkan output profiling di atas:

- **Ukuran data:** catat ukuran train dan validation yang ditampilkan pada bagian awal notebook.
- **Jumlah baris:** catat `jumlah_baris` untuk masing-masing split.
- **Tipe kolom:** catat skema Polars dan periksa apakah inferensi tipe DuckDB berbeda.
- **Null terbanyak:** urutkan nilai `*_null` pada ringkasan Polars; sebutkan nama kolom dan jumlahnya.
- **Anomali untuk Milestone 2:** periksa rekaman kosong/duplikat, teks atau label bahasa yang tidak valid, serta perbedaan skema train dan validation. Jangan mengasumsikan anomali sebelum memeriksa hasil.